### ISSUE TITLE
Error calling generation on a repo

### ISSUE THREAD

**Issue by ekarlso** [yoep/docker-archimate#1]
```
docker run -v $PWD:/src -w /src tool-archimate:latest /opt/Archi/Archi -application com.archimatetool.commandline.app -consoleLog -nosplash --modelrepository.loadModel . --html.createReport html
Unable to init server: Could not connect: Connection refused
!SESSION 2021-05-08 22:36:50.827 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.8
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -cleanConfig -application com.archimatetool.commandline.app --modelrepository.loadModel . --html.createReport html
Command-line arguments:  -os linux -ws gtk -arch x86_64 -cleanConfig -application com.archimatetool.commandline.app -consoleLog --modelrepository.loadModel . --html.createReport html

!ENTRY org.eclipse.osgi 4 0 2021-05-08 22:36:54.661
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4901)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1131)
	at org.eclipse.swt.widgets.Display.create(Display.java:1071)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:166)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:635)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:626)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:2330)
	at com.archimatetool.commandline.CentralScrutinizer.ensureDefaultDisplay(CentralScrutinizer.java:255)
	at com.archimatetool.commandline.CentralScrutinizer.runProviderOptions(CentralScrutinizer.java:159)
	at com.archimatetool.commandline.CentralScrutinizer.start(CentralScrutinizer.java:82)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
Unable to init server: Could not connect: Connection refused
Archi: Cannot open display: 
Archi:
An error has occurred. See the log file
/root/.archi4/.metadata/.log.
```

**Comment by ekarlso** [comment]
Turns out it was missing X options.

**Comment by fredmorin** [comment]
> Turns out it was missing X options.

How do you configure X options?
